// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCls4yNOfq4XWBumBfaiXFiYzc_HlID0Y4',
    appId: '1:359072128374:web:d9f7dc862635688169ae57',
    messagingSenderId: '359072128374',
    projectId: 'okumahizi',
    authDomain: 'okumahizi.firebaseapp.com',
    storageBucket: 'okumahizi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMe03WBJ0gul__HmFZqkxx5YtKe8zPjcs',
    appId: '1:359072128374:android:12af12ac73086bbe69ae57',
    messagingSenderId: '359072128374',
    projectId: 'okumahizi',
    storageBucket: 'okumahizi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqzJj_EevB5e16loa6YZzLqdrIVZaixkE',
    appId: '1:359072128374:ios:9b61b9562aaad14d69ae57',
    messagingSenderId: '359072128374',
    projectId: 'okumahizi',
    storageBucket: 'okumahizi.appspot.com',
    iosBundleId: 'com.example.deneme3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqzJj_EevB5e16loa6YZzLqdrIVZaixkE',
    appId: '1:359072128374:ios:9b61b9562aaad14d69ae57',
    messagingSenderId: '359072128374',
    projectId: 'okumahizi',
    storageBucket: 'okumahizi.appspot.com',
    iosBundleId: 'com.example.deneme3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCls4yNOfq4XWBumBfaiXFiYzc_HlID0Y4',
    appId: '1:359072128374:web:21da110610f0f8a269ae57',
    messagingSenderId: '359072128374',
    projectId: 'okumahizi',
    authDomain: 'okumahizi.firebaseapp.com',
    storageBucket: 'okumahizi.appspot.com',
  );
}
