name: Pull from GitHub

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'  # Her 15 dakikada bir çalıştırmak için

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull changes from GitHub
      run: git pull origin main
